### ISSUE TITLE
For metrics, wouldl ike to see a comparison US vs. Europe as a whole

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#12]
Action item from January 2018 PAB meeting

**Comment by atopal** [comment]
From the notes I can't quite tell anymore what the motivation for this question was. Please let me know if this makes sense:

MDN traffic is almost evenly divided between the Americas, Europe and Asia


Continent | Users | User Share
-- | -- | --
Europe | 2,423,877 | 33.94%
Americas | 2,250,740 | 31.52%
Asia | 2,151,295 | 30.13%
Africa | 180,498 | 2.53%
Oceania | 114,255 | 1.60%
(not set) | 20,282 | 0.28%

19% of user traffic falls on the US alone.

**Comment by robnyman** [comment]
Really interesting! Apparently a lot of room to grow in Africa and Oceania.
