### ISSUE TITLE
Look for opportunities to integrate MDN with 3rd party tools, docs, etc

### ISSUE THREAD

**Issue by Meggin** [mdn/pab#17]
We had a lengthy discussion about how to build tools on top of MDN srcs, like browser compatibility data, as well as drive more traffic to MDN from other 3rd party tools, docs, etc.

**Comment by Meggin** [comment]
I've started to create a Chrome DevTools browser compatibility extension, inspired by Firefox extension.

Here's a link to the Firebase extension that I'm gonna try and follow as a starting point: https://github.com/eduardoboucas/compat-report

And here's a link to the GitHub repo where I started to work on the extension... note that all I have done as of January 24 is the boilerplate, and a functioning panel-- next step is to get it to actually work with browser compatibility data!: https://github.com/Meggin/browser-compatibility-extension

Aiming to get more into the extension before the end of this week, maybe even a working prototype.

**Comment by robnyman** [comment]
🙌 🎉
