### ISSUE TITLE
Keep info on W3C specs up to date on MDN

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/pab#19]
MDN articles on features described in W3C specs usually have references to these specifications, with indication on their Recommendation track stage.

Right now, the alignment between this data and the actual progress of the specifications is manual. I have an early tool that allows to semi-automate the comparison between what's on MDN and what's in w3c database (see e.g. https://github.com/mdn/kumascript/pull/565), but it would be best if that check could be fully automated, or even better, if the data from MDN could be automatically pulled from W3C system.

There are some other related taxonomy questions:
* https://github.com/mdn/kumascript/issues/566
* the usage of editors draft vs latest TR draft
* the distinction between the various numbered versions of a given spec

**Comment by alispivak** [comment]
@dontcallmedom @chrisdavidmills  can this be closed?
