### ISSUE TITLE
ACTION:  Share info about MDN metrics by language as opposed to by country

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#2]
Action item from MDN PAB meeting, January 11-12.

**Comment by atopal** [comment]
Language | traffic share | cumulative
-- | -- | --
en | 54.8% | 54.8%
es | 8.2% | 73.8%
fr | 5.9% | 60.7%
zh-cn | 5.0% | 65.7%
ru | 4.2% | 86.0%
ja | 4.1% | 81.8%
de | 3.8% | 77.7%
pt-br | 2.7% | 88.7%
pl | 1.7% | 90.4%
ko | 1.4% | 91.8%
it | 1.3% | 94.0%
zh-tw | 0.9% | 92.7%
nl | 0.8% | 94.8%
tr | 0.5% | 95.3%


I removed the country codes for all languages and looked at the aggregated data. 

For reference, traffic by country:

Country | Users | traffic share | cumulative
-- | -- | -- | --
United States | 1,343,076 | 18.7% | 18.7%
India | 649,674 | 9.1% | 27.8%
France | 349,903 | 4.9% | 32.6%
Japan | 327,412 | 4.6% | 37.2%
China | 323,931 | 4.5% | 41.7%
Germany | 299,633 | 4.2% | 45.9%
United Kingdom | 260,102 | 3.6% | 49.5%
Brazil | 227,141 | 3.2% | 52.7%
Russia | 218,756 | 3.0% | 55.7%
Spain | 203,946 | 2.8% | 58.6%
Mexico | 189,602 | 2.6% | 61.2%
Canada | 179,120 | 2.5% | 63.7%
Poland | 144,293 | 2.0% | 65.7%
Ukraine | 133,750 | 1.9% | 67.6%
Italy | 110,328 | 1.5% | 69.1%
South Korea | 105,984 | 1.5% | 70.6%
Australia | 91,862 | 1.3% | 71.9%
Indonesia | 90,766 | 1.3% | 73.1%
Netherlands | 89,688 | 1.2% | 74.4%
Colombia | 82,739 | 1.2% | 75.5%
Philippines | 73,645 | 1.0% | 76.6%
Taiwan | 60,498 | 0.8% | 77.4%
Sweden | 57,954 | 0.8% | 78.2%
Switzerland | 50,098 | 0.7% | 78.9%
Turkey | 49,841 | 0.7% | 79.6%

**Comment by robnyman** [comment]
Thanks!
