### ISSUE TITLE
Shared best practices for writing up examples in specs and documentation

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/pab#22]
Similar to #21, I think MDN has probably accumulated (formally or informally) lots of best practices as to what constitutes a good introductory example - it would be useful to get these best practices shared with W3C groups and editors.

**Comment by chrisdavidmills** [comment]
@dontcallmedom the guideline you want are here:

* https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_samples
* https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Code_sample_style_and_formatting

**Comment by chrisdavidmills** [comment]
I think this can be closed.
