### ISSUE TITLE
Document workflow for transitioning dev-oriented content (incl. explainer) from W3C to MDN

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/pab#23]
Spec producing groups sometimes produce developer-oriented content as part of the spec development process: sometimes tutorials, primers, and more and more often, especially under the impulsion of the TAG, explainers (which focus on how a given feature would be used rather than how it should be spec'd).

We should document workflows to facilitate the transition of that content from W3C to MDN when wished for - the simplest thing is to advertise points of contacts (which worked well enough in the case of https://github.com/w3c/payment-request-info/issues/4 ) but there may be more opportunities.

**Comment by chrisdavidmills** [comment]
I have written a slightly more general article about migrating content to MDN:

https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Migrate_external_content_to_MDN

Is this the kind of thing you had in mind? Let me know what changes you'd like to see.

**Comment by chrisdavidmills** [comment]
Closing this; I think this is fixed now.
