### ISSUE TITLE
Highlight feedback loop from MDN articles to W3C specs / github repos

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/pab#25]
MDN has a lot more direct reach to developers - it would be great if that could be used as a conduit to bringing input and feedback to the standardization process.

Ideas include:
* add links to the github repos where the specs are being developed (I have the data that match specs to repos for the most part)
* establish workflows by which groups/editors can ask to get input from MDN readers on specific questions (e.g. ergonomy of a given API)
* tightly couple technologies labeled as "experimental" with requests for feedback
* use MDN as a way to recruit developers for user-testing of W3C specs, maybe based on the experience MDN has in driving remote user-testing sessions

**Comment by chrisdavidmills** [comment]
We already link to the specs from the "Specifications" section of each reference article (e.g. https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Specifications). Maybe we could add a fourth column along the lines of "Development repo" containing a link to the repo for each spec?

This would facilitate the workflow somewhat for readers to give feedback on specs. Although you are much more likely to want feedback when spec are experimental (which we have already talked about in https://github.com/mdn/pab/issues/58)

In terms of recruiting developers for user testing using MDN, I am not so sure about this? It might be worth talking to @atopal about how we recruited people for the MDN user testing sessions, to see if any of that could be applied to your use cases?

**Comment by dontcallmedom** [comment]
> We already link to the specs from the "Specifications" section of each reference article (e.g. https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Specifications). Maybe we could add a fourth column along the lines of "Development repo" containing a link to the repo for each spec?

I think the 4th column idea is already a good one, indeed.

I was thinking more broadly that it would be useful if e.g. a WG identifies a question on which they would like to get more developer's input, there was a well-documented workflow for that question to highlighted in some way on the relevant MDN page(s).

> In terms of recruiting developers for user testing using MDN, I am not so sure about this? It might be worth talking to @atopal about how we recruited people for the MDN user testing sessions, to see if any of that could be applied to your use cases?

Yes, I would very much like to pick @atopal 's brain o nthis

**Comment by chrisdavidmills** [comment]
See also https://github.com/mdn/pab/issues/58#issuecomment-455680845

**Comment by alispivak** [comment]
@chrisdavidmills Can we close this issue?

**Comment by chrisdavidmills** [comment]
I think I'll close this one, and we can just track it in issue 58.
