### ISSUE TITLE
ACTION See if the people who work on confluence/WPT could output the data in a useful format.

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#30]
from January 2018 PAB meeting

**Comment by robnyman** [comment]
Started an e-mail thread with https://github.com/foolip and https://github.com/mdittmer about this to find out more

**Comment by r12a** [comment]
I don't see a link to the minutes of the PAB meeting, so i don't know what you discussed, but one thing you may need to consider is that WPT typically doesn't distinguish between which tests are aimed at determining whether a feature has basic support, and detailed tests looking at edge cases. 

It seems to me that MDN could be overwhelmed if they represented all the available test results for, for example, writing-mode support in CSS (a quick look in the directory shows over 1,600 files, most of which I think are tests).  Even the W3C i18n test suite page for just vertical text (https://w3c.github.io/i18n-tests/results/writing-mode-vertical), which is less edge-case oriented, probably has more tests in it than are useful for MDN.

**Comment by robnyman** [comment]
Yeah, WPT would be overwhelming, for sure. This is rather more about Confluence and possible data automation from there.

**Comment by jpmedley** [comment]
Here's the tool. https://github.com/mdittmer/mdn-confluence Mark has been working on this since mid January, I think.

**Comment by chrisdavidmills** [comment]
@r12a FYI, meeting notes can all be found here: https://github.com/mdn/pab

**Comment by r12a** [comment]
Got it. Thanks @robnyman @jpmedley @chrisdavidmills

**Comment by atopal** [comment]
Just wanted to note that Mark was at the Hack on MDN event in Paris and started creating PRs from  confluence data: https://github.com/mdn/browser-compat-data/pulls/mdittmer. So I guess the answer here is: yes 👍  :)

**Comment by jpmedley** [comment]
@r12a There would obviously need to be some kind of intermediate system to aggregate results in a way that's useful to MDN. Also in the absence of a completely automated system, I'll take a semi-automated system if speeds things up.

**Comment by mdittmer** [comment]
Update: I thought individuals might be interested in accessing the raw Confluence data. We are currently trying to improve the comprehensibility of the data model, but here's what works today:

[This link](https://storage.googleapis.com/web-api-confluence-data-cache/latest/json/org.chromium.apis.web.Release.json) contains releases in release date order. [This link](https://storage.googleapis.com/web-api-confluence-data-cache/latest/json/org.chromium.apis.web.GridRow.json) contains <`id` (API name), `data`> pairs where Boolean array elements in `data` correspond to whether or not releases (in release date order) ship the API.

I can update this bug when a better release/data binding model is available.

**Comment by chrisdavidmills** [comment]
From what I know of more recent work by @foolip and @vinyldarkscratch, this has now happened. Worth keeping this one open, or could I close it?

**Comment by foolip** [comment]
This can be closed. There are scripts in BCD to use the Confluence data, and more recently https://mdn-bcd-collector.appspot.com/ and associated scripts have been developed specifically for updating BCD.
