### ISSUE TITLE
Provide more information on what "supported" means on MDN

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#33]
- Determine if guidelines exist for the "supported" label on MDN
- If they do, share with PAB & get feedback
- If they don't, open an issue to get them written

**Comment by chrisdavidmills** [comment]
I'm assuming this is talking about definitions for terms used in BCD, such as "Basic support" and "Full support?

There have been other discussions around the former, see https://discourse.mozilla.org/t/basic-support-in-browser-compatibility-tables/26634/3

For the latter, I think "Full support" is a pretty simple concept — for the feature in question, "Full support" means "supports it completely, as expected". Anything less than this is either covered by "No support", or explained in a note. 

I'm bringing @Elchi3 on board this one as a co-assignee, so we can work it out together when he is back off holiday.

**Comment by alispivak** [comment]
@chrisdavidmills  Can we close this issue?

**Comment by chrisdavidmills** [comment]
Yes. We circumvented this issue by removing the "Basic support" label from the BCD tables. Other things are defined in our "Conventions and definitions" page.
