### ISSUE TITLE
Determine if we can automate PR assignments through a GitHub hook

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#36]
Look into if it would be possible to could check which browser data a PR changes with a GitHub hook, then add tags for that browser and assign reviewers as appropriate.

**Comment by chrisdavidmills** [comment]
Dom sent a PR that would do this; Florian to review. 

This also relies on the governance piece.

**Comment by dontcallmedom** [comment]
The tool is at https://github.com/dontcallmedom/bcd-review-bot/

**Comment by alispivak** [comment]
@dontcallmedom  @Elchi3 Has this PR been reviewed and accepted? Can we close this issue?

**Comment by Elchi3** [comment]
Tracked here now: https://github.com/mdn/browser-compat-data/issues/3127

tl;dr We're not interested in this at this stage, given there are no dedicated people from browser vendors who are willing look after their data in day-to-day pull request reviews (Google and Mozilla being the exception). We can re-consider if more reviewers (preferably from all vendors) are involved and there is a need to assign reviews orderly.
