### ISSUE TITLE
Review adding Web Bluetooth, Midi to content roadmap

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#4]
Action item from PAB meeting 11-12 January, 2018

**Comment by chrisdavidmills** [comment]
I've had a look into these two technologies, and have found out the following from Mozilla's viewpoint:

1. WebMIDI is being implemented slowly, I think in an engineer's spare time/whenever he can find a spare cycle, but isn't a high priority for us in the grand scheme of things.
2. Web Bluetooth doesn't seem to be anywhere on any roadmap, for us at least. I couldn't see any activity on this. 

So for now I've put them in a couple of spare slots in Q2. But can't really promise we'll be able to prioritize these. I've asked one of our engineering managers if he can give me any further details about these.

**Comment by chrisdavidmills** [comment]
OK, so not a priority right now. But they are recorded on the roadmap.
