### ISSUE TITLE
More information about snippets from Google team

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#44]
Find out about search relationship like Wikipedia, talk to Ilya. What would be best to include in a snippet, best data to surface in results.

**Comment by robnyman** [comment]
Sent Ilya an e-mail, will follow up when I know more.

**Comment by robnyman** [comment]
Hi, the best resources we can provide here are these two links:
- 
[
https://developers.google.com/search/docs/data-types/breadcrumb ](https://developers.google.com/search/docs/data-types/breadcrumb)
- [https://support.google.com/webmasters/answer/7451184](https://support.google.com/webmasters/answer/7451184)

Hope this helps!

**Comment by atopal** [comment]
Thanks for the pointers, Robert! We still have some work to do in this area.
