### ISSUE TITLE
Contact Daniel Davis at DuckDuckGo about their snippets

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#46]
Connect Daniel Davis & Kadir so he can get a better understanding about snippets on DuckDuckGo.

**Comment by chrisdavidmills** [comment]
Yay, Daniel rocks! I used to work with him at Opera ;-)

**Comment by chrisdavidmills** [comment]
We will revisit this later in 2019.

**Comment by torgo** [comment]
Is there still an issue with DDG snippets? Looks OK to me... 

<img width="483" alt="image" src="https://user-images.githubusercontent.com/287526/87929053-ba16ca80-ca7d-11ea-8b3b-1ea9b1bc6d77.png">

**Comment by chrisdavidmills** [comment]
These do look better now. Shall I close this?

**Comment by chrisdavidmills** [comment]
I've closed it. We can always reopen if needed.
