### ISSUE TITLE
Look into compatibility data integration with Webhint

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#52]
Create an issue with the Sonar team to start discussion about compatibility data integration

**Comment by alispivak** [comment]
Action item from January 2018 PAB meeting

**Comment by torgo** [comment]
Ping @molant.

**Comment by molant** [comment]
Hi @alispivak and @torgo!

We currently have a [compat hint using MDN's data](https://www.npmjs.com/package/@hint/hint-compat-api). It's still in  beta although we are doing good progress and have a few PRs to make it better and enable by default in the default configuration (hopefully next week?):

* https://github.com/webhintio/hint/pull/1696
* https://github.com/webhintio/hint/pull/1660
* https://github.com/webhintio/hint/pull/1596

[Here is the link to the integration discussion](https://github.com/webhintio/rfcs/issues/10#issuecomment-433424902)

We have a meeting this next Wednesday 23rd with @digitarald to discuss this and other subjects related to Firefox <--> webhint. Let us know if you want to join!

Adding @antross, he's the one driving and reviewing this effort.

**Comment by atopal** [comment]
Hi Anton, 
I’d like to join that call if possible to make sure you are aware of our plans for the compatibility data in 2019 and to align with you on your needs going forward. 

Best, 
Kadir

**Comment by dontcallmedom** [comment]
this got done
