### ISSUE TITLE
Start conversation with caniuse about MDN schema

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#54]
Talk to Fyrd about caniuse and MDN schema, would be great if we could all agree

**Comment by alispivak** [comment]
Action item for Kadir from January 2018 PAB meeting.

**Comment by alispivak** [comment]
@atopal can we close this issue? I believe the conversation has taken place...

**Comment by atopal** [comment]
Yes, will update the board at the next meeting on our progress.
