### ISSUE TITLE
PWA definition discussion in Paris (16-18 March)

### ISSUE THREAD

**Issue by alispivak** [mdn/pab#63]
Discuss PWA definition working group at Hack on MDN (Paris) this weekend in Paris with Ada, Pete and Patrick, follow up with PAB and wider interest group.

**Comment by alispivak** [comment]
Action item from March 2018 PAB meeting

**Comment by chrisdavidmills** [comment]
We didn't get time to discuss this in Paris, but some useful discussion has happened online; see https://github.com/mdn/pab/issues/8
