### ISSUE TITLE
Link to 2018 review slides isn't publicly available

### ISSUE THREAD

**Issue by robnyman** [mdn/pab#66]
The link in the [meeting notes from July 2018](https://github.com/mdn/pab/blob/master/meeting-notes/2018-07-notes.md) goes to a slide deck that isn't publicly available.

**Comment by chrisdavidmills** [comment]
Thanks for bringing this up; removed.

**Comment by robnyman** [comment]
So, that wasn't my attention. :-) The slides were quite good, and I'd love for more to be able to take part of that content.

**Comment by chrisdavidmills** [comment]
OK, let's check with Kadir to see if they could be shared.

@atopal , would it be appropriate to publicly share the "2018 in review" slides you presented at the last PAB meeting?

**Comment by atopal** [comment]
I think we can do that. I just need to clean some of it up. I hadn't thought of a larger audience when I put them together ;) Thanks for bringing this up, Robert!

**Comment by chrisdavidmills** [comment]
Cool, just let me know, and I'll add the link back in.
