### ISSUE TITLE
Discuss more about where web compatibility updates should live

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/pab#86]
On MDN, Insights subdomain, etc.?

Should we have a meeting about this, or brainstorm in a doc?

More context at [Web Platform Compatibilty updates on MDN](https://github.com/mdn/pab/blob/master/meeting-notes/2021-02-notes.md#web-platform-compatibilty-updates-on-mdn).

**Comment by robnyman** [comment]
I sent a cal invite for Tue next week for @Elchi3 and you to talk more. Feel free to add any additional people who should be in it.

**Comment by chrisdavidmills** [comment]
We definitely agreed that we should have a section about this on the insights site, so next step thre would be to talk about what form that should take.

I'd also be happy to have some links to the update information from the relevant landing pages on MDN (e.g. Grid landing page, or whatever)

I believe we also started talking about a plan whereby we could have some kind of milestones in the BCD itself, e.g. if all those features are supported in a browser, then it turns green, and we show that in a browser compat ribbpon at the top of the page...this is definitely a future plan, which would require scoping and work.
